app/__init__.py
import logging

from flask import Flask
from flask_cdn import CDN
from flask_uploads import configure_uploads
from raven.contrib.flask import Sentry

from app.version import __version__
import settings
from app.views import bp, files

sentry = Sentry()
cdn = CDN()


def create_app(config_name='settings'):
    app = Flask(
        __name__,
        static_folder='static',
        static_url_path=settings.STATIC_URL
    )

    app.config.from_object(config_name)

    if settings.SENTRY_DSN:
        sentry.init_app(
            app,
            dsn=settings.SENTRY_DSN,
            logging=True,
            level=logging.ERROR)
        sentry.client.release = __version__

    cdn.init_app(app)

    app.register_blueprint(bp)
    configure_uploads(app, files)

    return app

app/views.py
import pandas as pd
from io import BytesIO

import arrow
from flask import Blueprint, render_template, request, flash, redirect
from flask_uploads import UploadSet

from app.agents.mastercard import MasterCard
from app.agents.register import PROVIDERS_MAP
from app.utils import validate_headers, is_handback_file

bp = Blueprint('selene', __name__)
files = UploadSet('files', extensions=('csv',))


@bp.route("/mids", methods=['GET', 'POST'])
def index():
    input_field_name = 'input_file'
    messages = None

    if request.method == 'POST':
        if input_field_name not in request.files:
            flash('No file part', 'warning')
            return redirect(request.url)

        input_file = request.files[input_field_name]
        if input_file.filename == '':
            flash('No file selected', 'warning')
            return redirect(request.url)

        basename = files.get_basename(input_file.filename)
        if files.file_allowed(input_file, basename):
            try:
                messages = process_mids_file(input_file)
                flash('File uploaded', 'success')
            except Exception as e:
                flash('Error: {}'.format(e), 'danger')
        else:
            flash('Incorrect File type. Please upload a csv.', 'warning')

    return render_template('index.html', messages=messages)


def process_mids_file(file):
    timestamp = arrow.utcnow().format('DDMMYY_hhmmssSSS')

    # MIDs columns default to float type which could cause issues e.g removing leading 0s
    datatype_conversion = {agent_class.mids_col_name: str for agent_class in PROVIDERS_MAP.values()}
    datatype_conversion.update({'Scheme ID': str})

    bytes_content = file.stream.read()
    file = BytesIO(bytes_content)
    original_df = pd.read_csv(file, dtype=datatype_conversion)

    headers = list(original_df.columns.values)
    is_valid_headers, invalid_headers, missing_headers = validate_headers(headers)

    messages = []
    if is_valid_headers:
        dataframes = {}

        for provider in PROVIDERS_MAP:
            columns_to_drop = [agent_class.mids_col_name for name, agent_class in PROVIDERS_MAP.items()
                               if name != provider]

            dataframes[provider] = original_df.drop(columns_to_drop, axis=1)
            agent_instance = PROVIDERS_MAP[provider](dataframes[provider], timestamp)

            agent_instance.export()
            agent_instance.write_transaction_matched_csv()

            message = agent_instance.create_messages()
            messages.append(message)
    else:
        if is_handback_file(headers):
            file_copy = BytesIO(bytes_content)
            dataframe_with_footer = pd.read_csv(file_copy, sep='|', header=None, skiprows=1, dtype={23: str})
            dataframe = dataframe_with_footer.iloc[:-1]

            agent_instance = MasterCard(dataframe, timestamp, handback=True)
            messages = agent_instance.process_handback_file()
        else:
            invalid_message = ''
            missing_message = ''

            if invalid_headers:
                invalid_message = 'Invalid headers: {}'.format(invalid_headers)
            if missing_headers:
                missing_message = 'Missing headers: {}'.format(missing_headers)

            error_message = '<p style="margin-bottom: 0;">{}</p><p style="margin-bottom: 0;">{}</p>'

            raise ValueError(error_message.format(invalid_message, missing_message))

    return messages


@bp.route('/healthz', methods=['GET'])
def healthz():
    return ''

environment/__init__.py
"""
References:

https://wellfire.co/blog/easier-12-factor-django/
"""
import os
import re


def read_env():
    """Pulled from Honcho code with minor updates, reads local default
    environment variables from a .env file located in the project root
    directory.
    """
    try:
        with open('.env') as f:
            content = f.read()
    except IOError:
        content = ''

    for line in content.splitlines():
        m1 = re.match(r'\A([A-Za-z_0-9]+)=(.*)\Z', line)
        if m1:
            key, val = m1.group(1), m1.group(2)
            m2 = re.match(r"\A'(.*)'\Z", val)
            if m2:
                val = m2.group(1)
            m3 = re.match(r'\A"(.*)"\Z', val)
            if m3:
                val = re.sub(r'\\(.)', r'\1', m3.group(1))
            os.environ.setdefault(key, val)


def env_var(key, default=None):
    """Retrieves env vars and makes Python boolean replacements"""
    val = os.environ.get(key, default)
    if val == 'True':
        val = True
    elif val == 'False':
        val = False
    return val

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- App CSS -->
    <link href="{{ url_for('static', filename='css/layout.css') }}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="#">Bink</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <!-- Message Flashing -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div class=flashes>
          {% for category, message in messages %}
            <div class="alert alert-{{ category }}" style="text-align: center;">
                <p style="margin-bottom: 0;">{{ message|safe }}</p>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}

    <!-- Page Content -->
    <div class="container">
        {% block main %}{% endblock %}
    </div>

    <!-- JQuery -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- App scripts -->
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

  </body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block main %}
  <div class="container-fluid row">
    <div id="uploadFileFormDiv" class="col-6 text-center">
      <div>Upload MIDs file</div>

      <!-- Upload File form -->
      <form class="form-group" id="uploadFormOnboard" action="{{ url_for('selene.index') }}" method="post" enctype="multipart/form-data">
        <div class="input-group">
          <label class="input-group-btn" for="inputFileOnboard">
             <span class="btn btn-primary">
                  Browse <input class="form-control" type="file" name="input_file" required
                                id="inputFileOnboard" accept=".csv" style="display: none;">
             </span>
          </label>
          <input id="filenameOnboard" type="text" class="form-control form-input" readonly="">
        </div>
        <button class="btn btn-success upload-btn" id="uploadButtonOnboard" type="submit">Upload</button>
      </form>

    </div>
  </div>
  <div class="container-fluid row output-row">
    {% if messages %}
      {% for message in messages %}
        <div class="box output-content alert alert-success">
          {% for each in message %}
            <p class="output-text">{{ each }}</p>
          {% endfor %}
        </div>
      {% endfor %}
    {% endif %}
  </div>


{% endblock %}